# Generated by Django 3.1 on 2020-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200828_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
