# Generated by Django 3.1 on 2020-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200829_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='image/%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
